# Generated by Django 5.2.7 on 2025-10-07 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_negociacao', models.CharField(help_text='Identificação da negociação/contrato', max_length=255, verbose_name='Nome da Negociação')),
                ('status', models.CharField(choices=[('VALIDACAO_DADOS', 'Validação de dados'), ('ANALISE_CREDITO', 'Análise de crédito'), ('ELABORACAO_CONTRATO', 'Elaboração do contrato'), ('REQUISICAO_VISTORIA', 'Requisição de vistoria'), ('MINUTA_APROVACAO', 'Minuta em aprovação'), ('ASSINATURA_ELETRONICA', 'Assinatura eletrônica do contrato'), ('REQUISICAO_LANCAMENTO', 'Requisição de lançamento financeiro'), ('CONTRATO_ASSINADO', 'Contrato assinado'), ('CONTRATO_CANCELADO', 'Contrato cancelado')], db_index=True, default='VALIDACAO_DADOS', max_length=30, verbose_name='Status')),
                ('locatario_nome', models.CharField(max_length=255, verbose_name='Nome do Locatário')),
                ('locatario_tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Locatário')),
                ('locatario_documento', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('imovel_endereco', models.CharField(max_length=500, verbose_name='Endereço do Imóvel')),
                ('imovel_codigo', models.CharField(blank=True, max_length=50, verbose_name='Código do Imóvel')),
                ('inicio_vigencia', models.DateField(blank=True, null=True, verbose_name='Início da Vigência')),
                ('fim_vigencia', models.DateField(blank=True, null=True, verbose_name='Fim da Vigência')),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Aluguel')),
                ('tipo_garantia', models.CharField(choices=[('CAUCAO', 'Caução'), ('FIADOR', 'Fiador'), ('SEGURO', 'Seguro Fiança'), ('TITULO', 'Título de Capitalização'), ('NENHUMA', 'Nenhuma')], default='NENHUMA', max_length=20, verbose_name='Tipo de Garantia')),
                ('data_entrada_fase', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada na Fase Atual')),
                ('prazo_fase_dias', models.IntegerField(default=5, help_text='Prazo esperado para conclusão da fase atual', verbose_name='Prazo da Fase (dias)')),
                ('motivo_cancelamento', models.TextField(blank=True, help_text='Obrigatório ao mover para status CONTRATO_CANCELADO', verbose_name='Motivo do Cancelamento')),
                ('possui_anexos', models.BooleanField(default=False, verbose_name='Possui Anexos')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['status', 'fim_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='AnexoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='contratos/anexos/%Y/%m/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('VALIDACAO_DADOS', 'Validação de dados'), ('ANALISE_CREDITO', 'Análise de crédito'), ('ELABORACAO_CONTRATO', 'Elaboração do contrato'), ('REQUISICAO_VISTORIA', 'Requisição de vistoria'), ('MINUTA_APROVACAO', 'Minuta em aprovação'), ('ASSINATURA_ELETRONICA', 'Assinatura eletrônica do contrato'), ('REQUISICAO_LANCAMENTO', 'Requisição de lançamento financeiro'), ('CONTRATO_ASSINADO', 'Contrato assinado'), ('CONTRATO_CANCELADO', 'Contrato cancelado')], max_length=30, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(choices=[('VALIDACAO_DADOS', 'Validação de dados'), ('ANALISE_CREDITO', 'Análise de crédito'), ('ELABORACAO_CONTRATO', 'Elaboração do contrato'), ('REQUISICAO_VISTORIA', 'Requisição de vistoria'), ('MINUTA_APROVACAO', 'Minuta em aprovação'), ('ASSINATURA_ELETRONICA', 'Assinatura eletrônica do contrato'), ('REQUISICAO_LANCAMENTO', 'Requisição de lançamento financeiro'), ('CONTRATO_ASSINADO', 'Contrato assinado'), ('CONTRATO_CANCELADO', 'Contrato cancelado')], max_length=30, verbose_name='Status Novo')),
                ('alterado_em', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-alterado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['status', 'fim_vigencia'], name='contratos_c_status_9357fa_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['responsavel', 'status'], name='contratos_c_respons_26dcb9_idx'),
        ),
    ]
