# Generated by Django 5.2.7 on 2025-10-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_add_analise_credito_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='locatario_email',
            field=models.EmailField(blank=True, help_text='E-mail para contato', max_length=255, verbose_name='E-mail do Locatário'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='locatario_telefone',
            field=models.CharField(blank=True, help_text='Telefone para contato', max_length=20, verbose_name='Telefone do Locatário'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato_assinado_anexado',
            field=models.BooleanField(default=False, help_text='Obrigatório para mover para fase de Assinatura Eletrônica', verbose_name='Contrato Assinado Anexado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='laudo_vistoria_anexado',
            field=models.BooleanField(default=False, help_text='Obrigatório para mover para fase de Requisição de Vistoria', verbose_name='Laudo de Vistoria Anexado'),
        ),
    ]
