# Generated by Django 5.2.7 on 2025-10-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_add_email_telefone_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='observacoes_gerais',
            field=models.TextField(blank=True, help_text='Campo livre para anotações e informações complementares sobre o contrato', verbose_name='Observações Gerais'),
        ),
    ]
